
server:
  applicationConnectors:
    - type: http
      port: 2000
  adminConnectors: []

logging:
  level: INFO
  appenders:
    - type: console
      threshold: UTC
      target: stdout
      logFormat: "[%d{HH:mm:ss yyyy-MM-dd}] [%level] %msg%n"

database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: "jdbc:mysql://localhost:3306/db_connect"
  user: splunk_user
  minSize: 8
  maxSize: 32

